### ISSUE TITLE
Request to provide classifier weights for imagenet-cls and cub200-cls

### ISSUE THREAD

**Issue by shakeebmurtaza** [weijun88/SPOL#1]
Hi,
Could you please provide weights for classifier used in these folders (imagenet-cls and cub200-cls)

**Comment by weijun-arc** [comment]
We do not save the weights for cub200-cls, but it is very easy for you to train the model by yourself. Imagenet-cls does not need the training process, you could directly run the `python test.py` to get the classification results.

**Comment by shakeebmurtaza** [comment]
Thanks
