### ISSUE TITLE
train.txt 和var.txt

### ISSUE THREAD

**Issue by Zhao-fan** [weijun88/SPOL#2]
您好！请问您代码里面的train.txt和var.txt文件是怎么生成的？能否分享一下。

**Comment by weijun-arc** [comment]
不好意思，我们没有保留生成得脚本。
不过你可以根据 readme 里面的链接下载对应数据集，里面有标注文件；
然后自己写个python程序转换为 txt 格式的文件；
或者直接使用我们提供的标注即可

**Comment by Zhao-fan** [comment]
好的，谢谢！
