### ISSUE TITLE
Why is the last count number 49985?

### ISSUE THREAD

**Issue by SejinPark99** [weijun88/SPOL#4]
Hello. I am interested in your research and results.

So, when I run the code in imagenet-seg/test.py  with model-6000 that is from you , the following results come out. :

count=49985 | top1=0.60476 | top5=0.68324 | GT-Known=0.69819

I have three questions here.

First, Why is the last count number 49985? I think the last number should be 49999.

Second, Is the last Gt-known(In my result, 0.69819) the overall result of the validation set?

Third, Why do I get better results than a paper when I run a given code?

Thank you. I look forward to your reply and hope you do better research. :+1: 👍

**Comment by weijun-arc** [comment]
1. Some images without bounding boxes annotations are filtered out, see  [here](https://github.com/weijun88/SPOL/blob/7a9d98504dfc91e342fa5494dd9a8514abd57e37/imagenet-seg/test.py#L82)
2. Yes, the Gt-known is based on the validation set
3. After the paper submission, some minor code errors are corrected.

**Comment by SejinPark99** [comment]
> 1. Some images without bounding boxes annotations are filtered out, see  [here](https://github.com/weijun88/SPOL/blob/7a9d98504dfc91e342fa5494dd9a8514abd57e37/imagenet-seg/test.py#L82)
> 2. Yes, the Gt-known is based on the validation set
> 3. After the paper submission, some minor code errors are corrected.

Thank you very much for your reply. I totally understood. I hope your research will be better. Thank you. :+1:
